# Generated by Django 4.2 on 2023-04-18 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_pool_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scores.pool'),
        ),
    ]
