# Generated by Django 4.2 on 2023-04-19 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_match_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='members',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pool',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.tournament'),
        ),
    ]
