# Generated by Django 4.2 on 2023-04-18 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_match_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scores.tournament'),
            preserve_default=False,
        ),
    ]
