# Generated by Django 4.2 on 2023-04-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_team_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
    ]
