# Generated by Django 4.2 on 2023-04-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_match_members_alter_pool_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
