# Generated by Django 4.2 on 2023-04-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_remove_match_members_team_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
