# Generated by Django 4.2 on 2023-04-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0009_alter_team_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scores.pool'),
        ),
    ]
