# Generated by Django 4.2 on 2023-04-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0011_article_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scores.match'),
        ),
    ]
