# Generated by Django 4.2 on 2023-04-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0012_commentaire_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='article',
        ),
    ]
