# Generated by Django 4.2 on 2023-04-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0013_alter_commentaire_options_remove_commentaire_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
