# Generated by Django 4.2 on 2023-04-20 19:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scores', '0014_delete_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentaire',
            new_name='Comment',
        ),
    ]
