# Generated by Django 4.2 on 2023-04-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0015_rename_commentaire_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ranking',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
