# Generated by Django 4.2 on 2023-04-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0016_team_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
